language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "k9W0219kffzhVyEfeHlaTwUa9FV1UqPaC9oXbm2EtqRLfGzQXgx/Qqyp5JmvDS9dYpHPrizurpzKfhbwtzTEhlEXHcfEiGiaoeCLSu0BnS2ej
4ifUH6G29jNfFOhDwq1wNNUoH3UurJJKyxR/OdEgIkneKaBm/G3dDX6RkDpbJzkWMuw3Ati6udq9qsy9r+p7E+UHnBhCksY5Az6J3S4+et9PNGnvIVXKWc4I
gFDOVdrTCvsvlFe6IK94qmiIwX/MxhpLyR7OnAWMBXNS/sCq8qJwgqfhkGq8jtLQ+yEf8oDlP5xUYW6BIGl+oufADVWYS5lHIC+4CkM5obQ+E9/Vcz3eEdA3
dTNlP+pRxPtAEdS/gJ7iLNa6B5P2DGsd8ArRBfXPEuaadtec2cICk+fjZZynWRaRZj8mRdEa6usnvlGQfqydDaYSNxJl2ZcXVIxtWoVv5rR6frJOPcLYXaVP
aL3m1WdQYvVyrZnlI/Va9oQV26mbY4+zWwX7nOe27bXcZ8RUSyVGCkcXBE8+sOmZERJEKn+JKmOHwGf3mwJfrphsa/qmR5mulSaNiRrhAK6St3OjvxOnFPSV
VCAPGtOG+B/Cz73zD9s66jhKj3pWGZtWEWtzv9bxjkGaBPsKnKdjvMWqd+LeAsQ+KPgemapASEs7czPGsliFVDtGlDz3SI="

jdk:
  - oraclejdk8
  
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -P jdeps

script:
  - mvn test -B -P coverage
  
cache:
  directories:
  - $HOME/.m2

after_success:
  - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
  - bash <(curl -s https://codecov.io/bash)
